import { createClient } from "npm:@supabase/supabase-js@2";
import { SignJWT, importPKCS8 } from "npm:jose@6";

type Job={id:string;client_id:string;project_id:string;job_type:string;payload?:Record<string,unknown>|null};
type JsonRecord=Record<string,unknown>;
type Admin=ReturnType<typeof createClient<any>>;
const workerName="build-business-seo-artifacts";
const jsonHeaders={"Content-Type":"application/json"};

function secret(name:string){const v=Deno.env.get(name)?.trim();if(!v)throw new Error(`Missing protected secret: ${name}`);return v;}
function response(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:jsonHeaders});}
async function timedFetch(input:string,init:RequestInit={},timeoutMs=15000){const c=new AbortController();const t=setTimeout(()=>c.abort(),timeoutMs);try{return await fetch(input,{...init,signal:c.signal});}finally{clearTimeout(t);}}
async function readJson(res:Response){const text=await res.text();if(!text)return null;try{return JSON.parse(text);}catch{return {message:text};}}
function normalizeJob(value:unknown):Job|null{if(value==null)return null;let v=value;if(typeof v==="string")v=JSON.parse(v);if(Array.isArray(v))v=v[0]??null;if(!v||typeof v!=="object")throw new Error("Invalid SEO job.");const j=v as Job;if(!j.id||!j.client_id||!j.project_id||!j.job_type)throw new Error("SEO job missing ids.");return j;}
const ghHeaders=(token:string)=>({Accept:"application/vnd.github+json",Authorization:`Bearer ${token}`,"X-GitHub-Api-Version":"2022-11-28","Content-Type":"application/json"});
const netlifyHeaders=(token:string)=>({Authorization:`Bearer ${token}`,"Content-Type":"application/json"});

async function githubToken(){const appId=secret("GITHUB_APP_ID"),installationId=secret("GITHUB_APP_INSTALLATION_ID");const key=await importPKCS8(secret("GITHUB_APP_PRIVATE_KEY").replace(/\\n/g,"\n"),"RS256");const now=Math.floor(Date.now()/1000);const jwt=await new SignJWT({}).setProtectedHeader({alg:"RS256"}).setIssuer(appId).setIssuedAt(now-30).setExpirationTime(now+540).sign(key);const res=await timedFetch(`https://api.github.com/app/installations/${installationId}/access_tokens`,{method:"POST",headers:ghHeaders(jwt),body:JSON.stringify({permissions:{contents:"write",metadata:"read"}})});const body=await readJson(res);if(!res.ok||typeof body?.token!=="string")throw new Error(`GitHub installation token failed (${res.status}).`);return body.token as string;}
async function getRefSha(owner:string,repo:string,branch:string,token:string){const res=await timedFetch(`https://api.github.com/repos/${owner}/${repo}/git/ref/heads/${encodeURIComponent(branch)}`,{headers:ghHeaders(token)});if(res.status===404)return null;const body=await readJson(res);if(!res.ok)throw new Error(`GitHub ref lookup failed for ${branch} (${res.status}).`);return typeof body?.object?.sha==="string"?body.object.sha:null;}
async function ensureSafeBranch(owner:string,repo:string,branch:string,token:string,baseMainSha:string){if(branch==="main"||!branch.startsWith("safe/"))throw new Error("SEO writes require a safe branch.");const existing=await getRefSha(owner,repo,branch,token);if(existing)return existing;const res=await timedFetch(`https://api.github.com/repos/${owner}/${repo}/git/refs`,{method:"POST",headers:ghHeaders(token),body:JSON.stringify({ref:`refs/heads/${branch}`,sha:baseMainSha})});const body=await readJson(res);if(!res.ok&&res.status!==422)throw new Error(`GitHub safe branch creation failed (${res.status}): ${String(body?.message||"Unknown error")}`);if(res.status===422){const raced=await getRefSha(owner,repo,branch,token);if(!raced)throw new Error("GitHub safe branch was reported existing but could not be read.");return raced;}return String(body?.object?.sha||baseMainSha);}
async function getFile(owner:string,repo:string,branch:string,path:string,token:string){const res=await timedFetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}?ref=${encodeURIComponent(branch)}`,{headers:ghHeaders(token)});if(res.status===404)return null;const body=await readJson(res);if(!res.ok)throw new Error(`GitHub lookup failed for ${path} (${res.status}).`);return body;}
async function putFile(owner:string,repo:string,branch:string,path:string,content:string,token:string,message:string){const existing=await getFile(owner,repo,branch,path,token);const sha=typeof existing?.sha==="string"?existing.sha:undefined;const encoded=btoa(unescape(encodeURIComponent(content)));const res=await timedFetch(`https://api.github.com/repos/${owner}/${repo}/contents/${path}`,{method:"PUT",headers:ghHeaders(token),body:JSON.stringify({message,content:encoded,branch,...(sha?{sha}:{})})});const body=await readJson(res);if(!res.ok)throw new Error(`GitHub write failed for ${path} (${res.status}): ${String(body?.message||"Unknown error")}`);const commit=String(body?.commit?.sha||"");if(!commit)throw new Error(`GitHub write for ${path} returned no commit SHA.`);return commit;}
async function compareMainToBranch(owner:string,repo:string,branch:string,token:string){const res=await timedFetch(`https://api.github.com/repos/${owner}/${repo}/compare/main...${encodeURIComponent(branch)}`,{headers:ghHeaders(token)});const body=await readJson(res);if(!res.ok)throw new Error(`GitHub SEO compare failed (${res.status}).`);return String(body?.status||"");}
async function fastForwardMain(owner:string,repo:string,sha:string,token:string){const res=await timedFetch(`https://api.github.com/repos/${owner}/${repo}/git/refs/heads/main`,{method:"PATCH",headers:ghHeaders(token),body:JSON.stringify({sha,force:false})});const body=await readJson(res);if(!res.ok)throw new Error(`GitHub SEO main fast-forward failed (${res.status}): ${String(body?.message||"Unknown error")}`);}
async function sha256(text:string){const d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,"0")).join("");}
function cleanBaseUrl(value:unknown){const raw=String(value||"").trim();if(!raw)return "";const u=new URL(raw);if(u.protocol!=="https:")throw new Error("SEO canonical base URL must use HTTPS.");return `${u.protocol}//${u.host}`;}
function escXml(v:unknown){return String(v??"").replace(/[<>&'"]/g,c=>({"<":"&lt;",">":"&gt;","&":"&amp;","'":"&apos;",'"':"&quot;"}[c]||c));}

async function triggerNetlifyBuild(siteId:string,branch:string){const token=secret("NETLIFY_ACCESS_TOKEN");const res=await timedFetch(`https://api.netlify.com/api/v1/sites/${siteId}/builds?branch=${encodeURIComponent(branch)}&clear_cache=true`,{method:"POST",headers:netlifyHeaders(token),body:"{}"});const body=await readJson(res);if(!res.ok)throw new Error(`Netlify SEO build failed to start (${res.status}): ${String(body?.message||body?.error||"Unknown error")}`);return body as JsonRecord;}
async function findExactDeploy(siteId:string,branch:string,expectedCommit:string){const token=secret("NETLIFY_ACCESS_TOKEN");const res=await timedFetch(`https://api.netlify.com/api/v1/sites/${siteId}/deploys?per_page=30`,{headers:netlifyHeaders(token)});const body=await readJson(res);if(!res.ok||!Array.isArray(body))throw new Error(`Netlify SEO deploy lookup failed (${res.status}).`);const deploy=body.find((item:JsonRecord)=>String(item.branch||"")===branch&&String(item.commit_ref||"")===expectedCommit) as JsonRecord|undefined;if(!deploy)return null;if(String(deploy.state)==="error")throw new Error(`Netlify SEO deploy failed: ${String(deploy.error_message||"Unknown build error")}`);if(String(deploy.state)!=="ready")return null;const url=String(deploy.deploy_ssl_url||deploy.ssl_url||deploy.deploy_url||deploy.url||"");if(!url.startsWith("https://"))throw new Error("SEO deploy verification did not return an HTTPS URL.");return{id:String(deploy.id||""),url};}

async function queue(admin:Admin,job:Job,type:string,key:string,payload:JsonRecord,delayMs:number,priority:number){const r=await admin.rpc("enqueue_automation_job",{target_client_id:job.client_id,target_project_id:job.project_id,target_job_type:type,target_idempotency_key:key,target_payload:{execution_target:"edge",requires_external_worker:true,...payload},target_run_after:new Date(Date.now()+delayMs).toISOString(),target_priority:priority});if(r.error)throw new Error(`SEO queue failed for ${type}: ${r.error.message}`);return r.data;}
async function validateEligibility(admin:Admin,job:Job){const [client,project,config,approval]=await Promise.all([admin.from("clients").select("id,status,business_name").eq("id",job.client_id).single(),admin.from("projects").select("id,product_family_id").eq("id",job.project_id).eq("client_id",job.client_id).single(),admin.from("project_deployment_configs").select("id,github_owner,github_repo,netlify_site_id,production_url,auto_publish_locked").eq("project_id",job.project_id).eq("client_id",job.client_id).single(),admin.from("owner_approval_requests").select("id").eq("client_id",job.client_id).eq("request_type","website_setup_review").eq("status","accepted").limit(1).maybeSingle()]);if(!client.data||!["approved","active"].includes(String(client.data.status)))throw new Error("Client is not eligible for SEO automation.");if(!project.data||!approval.data)throw new Error("Original accepted owner approval is required for SEO automation.");const family=await admin.from("product_families").select("slug").eq("id",project.data.product_family_id).maybeSingle();if(family.data?.slug!=="business")throw new Error("SEO maintenance currently supports Business family only.");if(!config.data?.github_owner||!config.data?.github_repo||!config.data?.netlify_site_id)throw new Error("Project deployment infrastructure is incomplete.");if(config.data.auto_publish_locked!==true)throw new Error("NXQ auto-publish safety lock must remain enabled.");return{client:client.data,config:config.data,approval_id:approval.data.id};}

async function processRefresh(admin:Admin,job:Job){const ctx=await validateEligibility(admin,job);const [locationsRes,pagesRes]=await Promise.all([admin.from("client_locations").select("id,display_name,status,address_line1,address_line2,city,state_region,postal_code,country_code,phone,email,service_area,seo_slug").eq("client_id",job.client_id).neq("status","closed").order("is_primary",{ascending:false}),admin.from("client_location_pages").select("location_id,canonical_path,status").eq("project_id",job.project_id).in("status",["ready","published"])]);const baseUrl=cleanBaseUrl(ctx.config.production_url||Deno.env.get("NXQ_SEO_FALLBACK_BASE_URL"));if(!baseUrl)throw new Error("Verified HTTPS production URL is required before SEO maintenance publishing.");const token=await githubToken();const mainSha=await getRefSha(ctx.config.github_owner,ctx.config.github_repo,"main",token);if(!mainSha)throw new Error("GitHub main branch commit is unavailable.");const branch=`safe/seo-${job.project_id.slice(0,8)}-${job.id.slice(0,8)}`;await ensureSafeBranch(ctx.config.github_owner,ctx.config.github_repo,branch,token,mainSha);

  const locationById=new Map((locationsRes.data||[]).map(l=>[String(l.id),l]));const urls=[`${baseUrl}/`];for(const page of pagesRes.data||[]){const loc=locationById.get(String(page.location_id));const canonicalPath=String(page.canonical_path||"").trim();const fallbackPath=loc?.seo_slug?`/locations/${String(loc.seo_slug)}/`:"";const path=canonicalPath||fallbackPath;if(path)urls.push(new URL(path,baseUrl).toString());}const uniqueUrls=[...new Set(urls)];const sitemap=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${uniqueUrls.map(u=>`  <url><loc>${escXml(u)}</loc></url>`).join("\n")}\n</urlset>\n`;const robots=`User-agent: *\nAllow: /\nSitemap: ${baseUrl}/sitemap.xml\n`;const organization={"@context":"https://schema.org","@type":"Organization",name:String(ctx.client.business_name||"Business"),url:baseUrl};const localBusinesses=(locationsRes.data||[]).filter(l=>l.status==="active"&&l.seo_slug).map(l=>({"@context":"https://schema.org","@type":"LocalBusiness",name:String(l.display_name||ctx.client.business_name||"Business"),url:new URL(`/locations/${String(l.seo_slug)}/`,baseUrl).toString(),telephone:l.phone||undefined,email:l.email||undefined,address:{"@type":"PostalAddress",streetAddress:[l.address_line1,l.address_line2].filter(Boolean).join(" ")||undefined,addressLocality:l.city||undefined,addressRegion:l.state_region||undefined,postalCode:l.postal_code||undefined,addressCountry:l.country_code||"US"},areaServed:l.service_area||undefined}));const schema=JSON.stringify({organization,locations:localBusinesses},null,2)+"\n";

  const sitemapCommit=await putFile(ctx.config.github_owner,ctx.config.github_repo,branch,"sitemap.xml",sitemap,token,"NXQ: refresh sitemap");const robotsCommit=await putFile(ctx.config.github_owner,ctx.config.github_repo,branch,"robots.txt",robots,token,"NXQ: refresh robots");const sourceHead=await putFile(ctx.config.github_owner,ctx.config.github_repo,branch,"seo.schema.json",schema,token,"NXQ: refresh structured SEO data");const now=new Date().toISOString();const artifacts=[{artifact_type:"sitemap",git_path:"sitemap.xml",git_commit_sha:sitemapCommit,content_hash:await sha256(sitemap)},{artifact_type:"robots",git_path:"robots.txt",git_commit_sha:robotsCommit,content_hash:await sha256(robots)},{artifact_type:"organization_schema",git_path:"seo.schema.json",git_commit_sha:sourceHead,content_hash:await sha256(schema)}];for(const artifact of artifacts){const up=await admin.from("project_seo_artifacts").upsert({client_id:job.client_id,project_id:job.project_id,...artifact,status:"ready",canonical_base_url:baseUrl,last_generated_at:now,last_error:null,metadata:{branch,worker:workerName,url_count:uniqueUrls.length,location_count:localBusinesses.length}},{onConflict:"project_id,artifact_type"});if(up.error)throw new Error(`SEO artifact state failed: ${up.error.message}`);}

  const run=await admin.from("project_seo_refresh_runs").upsert({client_id:job.client_id,project_id:job.project_id,status:"generated",source_branch:branch,base_main_sha:mainSha,source_head_sha:sourceHead,last_error:null,metadata:{approval_id:ctx.approval_id,url_count:uniqueUrls.length,location_count:localBusinesses.length}},{onConflict:"project_id,source_head_sha"}).select("id").single();if(run.error||!run.data?.id)throw new Error(run.error?.message||"SEO refresh run could not be recorded.");const build=await triggerNetlifyBuild(ctx.config.netlify_site_id,branch);await admin.from("project_seo_refresh_runs").update({status:"preview_building",metadata:{approval_id:ctx.approval_id,url_count:uniqueUrls.length,location_count:localBusinesses.length,preview_build_id:build?.id||null},updated_at:now}).eq("id",run.data.id);const checkJob=await queue(admin,job,"website_project_seo_preview_check",`seo-run:${run.data.id}:preview:${sourceHead}`,{seo_refresh_run_id:run.data.id},30000,46);return{seo_refresh_run_id:run.data.id,branch,source_head_sha:sourceHead,preview_check_job_id:checkJob,artifacts};}

async function loadRun(admin:Admin,job:Job){const runId=String(job.payload?.seo_refresh_run_id||"");if(!runId)throw new Error("SEO maintenance job is missing refresh run id.");const run=await admin.from("project_seo_refresh_runs").select("*").eq("id",runId).eq("client_id",job.client_id).eq("project_id",job.project_id).single();if(run.error||!run.data)throw new Error(run.error?.message||"SEO refresh run not found.");return run.data as JsonRecord;}

async function processPreviewCheck(admin:Admin,job:Job){const ctx=await validateEligibility(admin,job);const run=await loadRun(admin,job);const deploy=await findExactDeploy(ctx.config.netlify_site_id,String(run.source_branch),String(run.source_head_sha));if(!deploy)throw new Error("Exact SEO branch preview commit is still building.");await admin.from("project_seo_refresh_runs").update({status:"preview_ready",preview_deploy_id:deploy.id,preview_url:deploy.url,preview_verified_at:new Date().toISOString(),last_error:null,updated_at:new Date().toISOString()}).eq("id",String(run.id));const promoteJob=await queue(admin,job,"website_project_seo_promote",`seo-run:${String(run.id)}:promote:${String(run.source_head_sha)}`,{seo_refresh_run_id:run.id},0,52);return{seo_refresh_run_id:run.id,preview_url:deploy.url,promote_job_id:promoteJob};}

async function processPromote(admin:Admin,job:Job){const ctx=await validateEligibility(admin,job);const run=await loadRun(admin,job);if(String(run.status)!=="preview_ready")throw new Error("SEO refresh is not preview-ready.");const token=await githubToken();const currentMain=await getRefSha(ctx.config.github_owner,ctx.config.github_repo,"main",token);const sourceHead=await getRefSha(ctx.config.github_owner,ctx.config.github_repo,String(run.source_branch),token);if(!currentMain||!sourceHead)throw new Error("GitHub SEO promotion refs are unavailable.");if(sourceHead!==String(run.source_head_sha))throw new Error("SEO source branch changed after preview verification.");if(currentMain!==String(run.base_main_sha)){
    await admin.from("project_seo_refresh_runs").update({status:"blocked",last_error:"Production main changed after SEO branch creation; regeneration queued.",updated_at:new Date().toISOString()}).eq("id",String(run.id));
    const regen=await queue(admin,job,"website_project_seo_refresh",`seo-rebase:${job.project_id}:${currentMain}`,{source:"main_changed_during_seo_promotion",replaces_seo_refresh_run_id:run.id},0,48);
    return{seo_refresh_run_id:run.id,promotion:"regeneration_queued",replacement_job_id:regen,current_main_sha:currentMain};
  }
  const compare=await compareMainToBranch(ctx.config.github_owner,ctx.config.github_repo,String(run.source_branch),token);if(!["ahead","identical"].includes(compare))throw new Error(`SEO production promotion requires clean fast-forward; compare status was ${compare||"unknown"}.`);await admin.from("project_seo_refresh_runs").update({status:"promoting",updated_at:new Date().toISOString()}).eq("id",String(run.id));if(sourceHead!==currentMain)await fastForwardMain(ctx.config.github_owner,ctx.config.github_repo,sourceHead,token);const build=await triggerNetlifyBuild(ctx.config.netlify_site_id,"main");await admin.from("project_seo_refresh_runs").update({status:"production_building",production_commit_sha:sourceHead,metadata:{...(run.metadata as JsonRecord||{}),production_build_id:build?.id||null,github_compare_status:compare,force_push:false},updated_at:new Date().toISOString()}).eq("id",String(run.id));const checkJob=await queue(admin,job,"website_project_seo_production_check",`seo-run:${String(run.id)}:production:${sourceHead}`,{seo_refresh_run_id:run.id},30000,54);return{seo_refresh_run_id:run.id,production_commit_sha:sourceHead,production_check_job_id:checkJob,force_push:false};}

async function processProductionCheck(admin:Admin,job:Job){const ctx=await validateEligibility(admin,job);const run=await loadRun(admin,job);const expected=String(run.production_commit_sha||run.source_head_sha||"");if(!expected)throw new Error("SEO production verification is missing expected commit.");const deploy=await findExactDeploy(ctx.config.netlify_site_id,"main",expected);if(!deploy)throw new Error("Exact SEO production commit is still building.");const now=new Date().toISOString();await admin.from("project_seo_refresh_runs").update({status:"published",production_deploy_id:deploy.id,production_url:deploy.url,production_commit_sha:expected,published_at:now,last_error:null,updated_at:now}).eq("id",String(run.id));await admin.from("project_seo_artifacts").update({status:"published",git_commit_sha:expected,last_verified_at:now,last_error:null,updated_at:now}).eq("project_id",job.project_id).eq("client_id",job.client_id);await admin.from("project_deployment_configs").update({production_url:deploy.url,last_deployed_commit:expected,last_deployment_status:"published"}).eq("id",ctx.config.id).eq("project_id",job.project_id).eq("client_id",job.client_id);await admin.from("automation_audit_log").insert({client_id:job.client_id,project_id:job.project_id,event_type:"business_seo_maintenance_published",actor_type:"backend",details:{seo_refresh_run_id:run.id,production_commit_sha:expected,production_deploy_id:deploy.id,production_url:deploy.url}});return{seo_refresh_run_id:run.id,status:"published",production_commit_sha:expected,production_url:deploy.url};}

async function processJob(admin:Admin,job:Job){switch(job.job_type){case"website_project_seo_refresh":return processRefresh(admin,job);case"website_project_seo_preview_check":return processPreviewCheck(admin,job);case"website_project_seo_promote":return processPromote(admin,job);case"website_project_seo_production_check":return processProductionCheck(admin,job);default:throw new Error("Unsupported SEO worker job type.");}}

Deno.serve(async(req)=>{if(req.method!=="POST")return response({ok:false,error:"Method not allowed."},405);if(req.headers.get("x-nxq-worker-token")!==secret("NXQ_AUTOMATION_WORKER_TOKEN"))return response({ok:false,error:"Unauthorized."},401);const admin=createClient(secret("SUPABASE_URL"),secret("SUPABASE_SERVICE_ROLE_KEY"),{auth:{persistSession:false}});let job:Job|null=null;try{const claim=await admin.rpc("claim_next_external_automation_job",{target_execution_target:"edge",worker_name:workerName,target_job_types:["website_project_seo_refresh","website_project_seo_preview_check","website_project_seo_promote","website_project_seo_production_check"]});if(claim.error)throw new Error(`SEO claim failed: ${claim.error.message}`);job=normalizeJob(claim.data);if(!job)return response({ok:true,claimed:false});const result=await processJob(admin,job);const done=await admin.rpc("complete_external_automation_job",{target_job_id:job.id,worker_name:workerName,target_result:result});if(done.error)throw new Error(`SEO completion failed: ${done.error.message}`);return response({ok:true,claimed:true,job_id:job.id,result});}catch(error){const message=error instanceof Error?error.message:"Unknown SEO automation error";if(job?.id)await admin.rpc("fail_external_automation_job",{target_job_id:job.id,worker_name:workerName,target_error:message});return response({ok:false,job_id:job?.id||null,error:message},500);}});
