import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, CheckCircle2, Clock3, FileClock, ReceiptText, Rocket, ShieldCheck, Sparkles, Wrench } from "lucide-react";
import { isSupabaseConfigured, supabase } from "../lib/supabaseClient";

type HistoryEvent={key:string;category:string;title:string;detail:string;status:string;occurred_at:string;href:string};
type Payment={id:string;provider:string;status:string;amount:number;currency:string;note?:string|null;recorded_at:string};
type History={business_name:string;summary:{published_deployments:number;completed_maintenance:number;published_changes:number;delivered_reports:number;recorded_payments:number};events:HistoryEvent[];payments:Payment[];claims_policy:string};
const icons={deployment:Rocket,maintenance:Wrench,change:Sparkles,report:FileClock,billing:ReceiptText,approval:ShieldCheck,account:CheckCircle2} as const;
function money(amount:number,currency:string){return new Intl.NumberFormat("en-US",{style:"currency",currency:currency||"USD"}).format(Number(amount||0));}

export function ClientValueHistory(){
  const [history,setHistory]=useState<History|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(true);
  useEffect(()=>{let active=true;async function load(){if(!isSupabaseConfigured||!supabase){if(active){setError("Supabase is not configured yet.");setLoading(false);}return;}const session=await supabase.auth.getSession();if(!session.data.session){window.location.replace("/portal/login");return;}const result=await supabase.rpc("current_client_value_history");if(!active)return;if(result.error)setError(result.error.message||"History could not load.");else setHistory(result.data as History);setLoading(false);}void load();return()=>{active=false;};},[]);
  const cards=useMemo(()=>history?[["Deployments",history.summary.published_deployments,Rocket],["Care tasks",history.summary.completed_maintenance,Wrench],["Published updates",history.summary.published_changes,Sparkles],["Value reports",history.summary.delivered_reports,FileClock],["Payment records",history.summary.recorded_payments,ReceiptText]] as const:[],[history]);
  return <main className="nxq-page"><section className="portal-shell value-history-page"><div className="panel-title panel-title-row"><div className="panel-title"><Sparkles size={22}/><div><p className="eyebrow">Recorded work, not marketing guesses</p><h1>NXQ value & history</h1><p className="subtle">A clear record of website launches, care work, published updates, reports, and billing entries.</p></div></div><a className="icon-btn" href="/client/business"><ArrowLeft size={16}/> Business</a></div>{error?<div className="auth-error" role="alert">{error}</div>:null}{loading?<div className="empty-state" role="status">Loading your NXQ history...</div>:null}{history?<><section className="value-summary-grid">{cards.map(([label,value,Icon])=><article className="panel value-summary-card" key={label}><Icon size={20}/><span>{label}</span><strong>{value}</strong></article>)}</section><section className="panel panel-wide"><div className="panel-title"><Clock3 size={20}/><div><h2>Website history</h2><p className="subtle">Events appear only when NXQ has matching backend evidence.</p></div></div>{history.events.length===0?<div className="empty-state">No recorded website events yet.</div>:<ol className="value-event-list">{history.events.map(event=>{const Icon=icons[event.category as keyof typeof icons]||CheckCircle2;return <li key={event.key}><Icon size={18}/><div><div className="panel-title panel-title-row"><strong>{event.title}</strong><span>{new Date(event.occurred_at).toLocaleString()}</span></div><p>{event.detail}</p><span className="status-summary">{event.status.replaceAll("_"," ")}</span></div><a className="icon-btn" href={event.href}>Details</a></li>;})}</ol>}</section><section className="panel panel-wide"><div className="panel-title"><ReceiptText size={20}/><div><h2>Payment records</h2><p className="subtle">Payments are shown exactly as stored. NXQ does not call a record an invoice or receipt unless that document was actually issued.</p></div></div>{history.payments.length===0?<div className="empty-state">No payment records have been added yet.</div>:<div className="value-payment-list">{history.payments.map(payment=><article key={payment.id}><div><strong>{money(payment.amount,payment.currency)}</strong><p>{payment.provider} · {payment.status.replaceAll("_"," ")} · {new Date(payment.recorded_at).toLocaleDateString()}</p>{payment.note?<p className="subtle">{payment.note}</p>:null}</div><span className="status-summary">recorded</span></article>)}</div>}</section></>:null}</section></main>;
}
