import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, Gift, RefreshCcw, ShieldCheck, Users } from "lucide-react";
import { isSupabaseConfigured, supabase } from "../lib/supabaseClient";

type Referral = { id: string; status: string; attributed_at: string; hold_until?: string | null; risk_score: number };
type Ledger = { id: string; entry_type: string; status: string; amount: number; remaining_amount: number; description: string; created_at: string };
type Dashboard = { profile?: { referral_code?: string; status?: string }; program?: { enabled?: boolean; reward?: number; first_month_discount?: number; minimum_payment?: number; hold_days?: number; grant_enrollment_open?: boolean; grant_monthly_cost_cap?: number }; balances?: { pending?: number; available?: number; applied?: number }; referrals?: Referral[]; ledger?: Ledger[]; grant_application?: { status?: string; cohort_position?: number } | null; grant_award?: { status?: string; monthly_nxq_cost_cap?: number } | null };

export function ClientRewards() {
  const [data,setData]=useState<Dashboard>({}); const [code,setCode]=useState(""); const [statement,setStatement]=useState("");
  const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{ if(!isSupabaseConfigured||!supabase){setError("Supabase is not configured yet.");return;} setBusy(true);setError("");const result=await supabase.rpc("nxq_referral_dashboard");setBusy(false);if(result.error){setError(result.error.message);return;}setData((result.data||{}) as Dashboard);},[]);
  useEffect(()=>{void load();},[load]);
  async function call(name:string,args:Record<string,unknown>,message:string){if(!supabase)return;setBusy(true);setError("");setNotice("");const result=await supabase.rpc(name,args);setBusy(false);if(result.error){setError(result.error.message);return;}setNotice(message);await load();}
  const program=data.program||{}; const balances=data.balances||{};
  const shareUrl=data.profile?.referral_code?`${window.location.origin}/portal/signup?ref=${data.profile.referral_code}`:"";
  return <main className="nxq-page"><section className="portal-shell">
    <div className="panel-title panel-title-row"><div className="panel-title"><Gift size={22}/><div><h1>Rewards & Founding Grant</h1><p className="subtle">Referral credits are non-cash, non-transferable, and can never reduce an invoice below $10.</p></div></div><div className="client-control-row"><a className="icon-btn" href="/client"><ArrowLeft size={16}/> Portal</a><button className="icon-btn" onClick={()=>void load()} disabled={busy}><RefreshCcw size={16}/> Refresh</button></div></div>
    {error?<div className="auth-error">{error}</div>:null}{notice?<div className="auth-success">{notice}</div>:null}
    <div className="owner-detail-grid"><section className="panel panel-wide"><h2>Your referral link</h2>{program.enabled?<><p className="subtle">Your friend gets ${Number(program.first_month_discount||10).toFixed(0)} off their first invoice. You earn ${Number(program.reward||10).toFixed(0)} after their first verified payment clears the {program.hold_days||14}-day review period.</p><input className="auth-input" readOnly value={shareUrl}/><button className="wide-btn" disabled={!shareUrl} onClick={()=>void navigator.clipboard.writeText(shareUrl)}><Users size={16}/> Copy referral link</button></>:<div className="empty-state">The owner has not opened referrals yet. Your code is reserved and ready.</div>}</section>
    <section className="panel panel-wide"><h2>Credit balance</h2><div className="client-control-row"><span className="status-summary">Available ${Number(balances.available||0).toFixed(2)}</span><span className="status-summary">Pending ${Number(balances.pending||0).toFixed(2)}</span><span className="status-summary">Applied ${Number(balances.applied||0).toFixed(2)}</span></div><p className="subtle">Credits roll forward until used. They do not recur monthly and cannot create a negative bill, cash payout, or amount owed by NXQ.</p></section></div>
    <section className="panel panel-wide"><h2>Have a referral code?</h2><div className="client-control-row"><input className="auth-input" value={code} maxLength={20} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="NXQ referral code"/><button className="wide-btn" disabled={busy||code.length<8||!program.enabled} onClick={()=>void call("nxq_claim_referral",{target_referral_code:code},"Referral attached. Your bounded first-invoice credit is ready.")}>Apply code</button></div></section>
    <section className="panel panel-wide"><div className="panel-title"><ShieldCheck size={20}/><div><h2>NXQ Founding Business Grant</h2><p className="subtle">Ten owner-selected awards among the first 10,000 verified paying clients. One base site per business, capped at ${Number(program.grant_monthly_cost_cap||50).toFixed(0)} NXQ cost per month; no cash value, transfer, domain, ads, premium APIs, ecommerce fees, or outside-provider costs.</p></div></div>{data.grant_award?<div className="auth-success">Award status: {data.grant_award.status}</div>:data.grant_application?<div className="status-summary">Application: {data.grant_application.status} · cohort position {data.grant_application.cohort_position}</div>:program.grant_enrollment_open?<><textarea className="auth-input" rows={4} value={statement} onChange={e=>setStatement(e.target.value)} placeholder="Tell NXQ how a managed website would help your business."/><button className="wide-btn" disabled={busy||statement.trim().length<30} onClick={()=>void call("nxq_submit_founding_grant_application",{target_statement:statement},"Founding Grant application submitted for owner review.")}>Submit application</button></>:<div className="empty-state">Applications remain closed until legal review and owner activation are complete.</div>}</section>
    <div className="owner-detail-grid"><section className="panel panel-wide"><h2>Referrals</h2>{(data.referrals||[]).length===0?<div className="empty-state">No referrals yet.</div>:(data.referrals||[]).map(row=><div className="owner-message-card" key={row.id}><strong>{row.status.replaceAll("_"," ")}</strong><span className="subtle">Attributed {new Date(row.attributed_at).toLocaleDateString()} · risk review {row.risk_score}/100</span></div>)}</section><section className="panel panel-wide"><h2>Credit ledger</h2>{(data.ledger||[]).length===0?<div className="empty-state">No credit entries yet.</div>:(data.ledger||[]).map(row=><div className="owner-message-card" key={row.id}><strong>{row.description}</strong><span className="subtle">{row.status} · ${Number(row.amount).toFixed(2)} · ${Number(row.remaining_amount).toFixed(2)} remaining</span></div>)}</section></div>
  </section></main>;
}
