import { useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, CircleAlert, Globe2, RefreshCcw } from "lucide-react";
import { isSupabaseConfigured, supabase } from "../lib/supabaseClient";

type Domain={id:string;domain_name:string;status:string;automation_state:string;automation_enabled:boolean;dns_status:string;ssl_status:string;last_checked_at:string|null;next_check_at:string;automation_error:string|null;action_required_message:string|null;dns_instructions:string|null;registrar_name:string|null;dns_provider:string|null};

export function ClientDomainStatus(){
  const [domains,setDomains]=useState<Domain[]>([]);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState<string|null>(null);const [loading,setLoading]=useState(true);
  async function load(){if(!isSupabaseConfigured||!supabase){setError("Supabase is not configured yet.");setLoading(false);return;}const session=await supabase.auth.getSession();const user=session.data.session?.user;if(!user){window.location.replace("/portal/login");return;}const client=await supabase.from("clients").select("id").eq("auth_user_id",user.id).maybeSingle();if(client.error||!client.data){setError(client.error?.message||"Client account not found.");setLoading(false);return;}const rows=await supabase.from("client_domains").select("id,domain_name,status,automation_state,automation_enabled,dns_status,ssl_status,last_checked_at,next_check_at,automation_error,action_required_message,dns_instructions,registrar_name,dns_provider").eq("client_id",client.data.id).order("requested_at",{ascending:false});if(rows.error){setError(rows.error.message);setLoading(false);return;}setDomains((rows.data||[]) as Domain[]);setLoading(false);}
  useEffect(()=>{void load();},[]);
  async function recheck(domain:Domain){if(!supabase)return;setBusy(domain.id);setError("");setNotice("");const r=await supabase.rpc("current_client_request_domain_recheck",{target_domain_id:domain.id});if(r.error)setError(r.error.message);else{setNotice(`NXQ queued a fresh domain check for ${domain.domain_name}.`);await load();}setBusy(null);}
  function label(state:string){return state.replaceAll("_"," ");}
  return <main className="nxq-page"><section className="portal-shell"><div className="panel-title panel-title-row"><div className="panel-title"><Globe2 size={22}/><div><h1>Domain status</h1><p className="subtle">NXQ keeps checking DNS and SSL automatically. If your registrar needs a manual change, the exact action appears here.</p></div></div><a className="icon-btn" href="/client/settings"><ArrowLeft size={16}/>Settings</a></div>{error?<div className="auth-error" role="alert">{error}</div>:null}{notice?<div className="auth-success">{notice}</div>:null}{loading?<div className="empty-state">Loading domain status...</div>:null}{!loading&&domains.length===0?<div className="empty-state">No domain has been submitted yet.</div>:null}<div className="owner-message-list">{domains.map((domain)=>{const connected=domain.automation_state==="connected"&&domain.ssl_status==="ready";const action=domain.automation_state==="action_required"||Boolean(domain.action_required_message);return <article className="owner-message-card" key={domain.id}><div className="panel-title panel-title-row"><div className="panel-title">{connected?<CheckCircle2 size={18}/>:action?<CircleAlert size={18}/>:<RefreshCcw size={18}/>}<div><strong>{domain.domain_name}</strong><p className="subtle">{label(domain.automation_state)} · DNS {label(domain.dns_status)} · SSL {label(domain.ssl_status)}</p></div></div><span className="status-summary">{connected?"connected":action?"action required":"checking"}</span></div>{domain.action_required_message?<div className="auth-error">{domain.action_required_message}</div>:null}{domain.dns_instructions?<p>{domain.dns_instructions}</p>:null}{domain.automation_error&&!action?<p className="subtle">{domain.automation_error}</p>:null}<p className="subtle">Registrar: {domain.registrar_name||"not specified"} · DNS provider: {domain.dns_provider||"not specified"}</p>{domain.last_checked_at?<p className="subtle">Last checked {new Date(domain.last_checked_at).toLocaleString()}</p>:null}<button className="icon-btn" type="button" disabled={busy===domain.id||!domain.automation_enabled||connected} onClick={()=>void recheck(domain)}><RefreshCcw size={15}/>{busy===domain.id?"Queuing...":connected?"Connected":"Check again"}</button></article>;})}</div></section></main>;
}
