import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, RefreshCcw, ShieldAlert, Target } from "lucide-react";
import { isSupabaseConfigured, supabase } from "../lib/supabaseClient";

type Growth = { settings?: Record<string,unknown>; summary?: Record<string,number>; grant_applications?: Array<Record<string,unknown>> };
type Finder = { settings?: Record<string,unknown>; summary?: Record<string,number>; recent_runs?: Array<Record<string,unknown>> };
export function OwnerGrowthCenter(){
  const [growth,setGrowth]=useState<Growth>({});const [finder,setFinder]=useState<Finder>({});const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);const [niche,setNiche]=useState("tree_services");const [geography,setGeography]=useState("Dallas, Texas");
  const load=useCallback(async()=>{if(!isSupabaseConfigured||!supabase){setError("Supabase is not configured yet.");return;}setBusy(true);setError("");const [a,b]=await Promise.all([supabase.rpc("owner_growth_dashboard"),supabase.rpc("owner_client_finder_dashboard")]);setBusy(false);if(a.error||b.error){setError(a.error?.message||b.error?.message||"Unable to load growth controls.");return;}setGrowth((a.data||{}) as Growth);setFinder((b.data||{}) as Finder);},[]);useEffect(()=>{void load();},[load]);
  async function fictional(){if(!supabase)return;setBusy(true);setError("");setNotice("");const result=await supabase.functions.invoke("discover-sales-prospects",{body:{fictional:true,niche_key:niche,geography,limit:5}});setBusy(false);if(result.error||result.data?.ok===false){setError(result.data?.error||result.error?.message||"Fictional discovery failed.");return;}setNotice("Five fictional, permanently suppressed prospects were created. Nothing was sent.");await load();}
  const gs=growth.settings||{};const g=growth.summary||{};const fs=finder.settings||{};const f=finder.summary||{};
  return <main className="nxq-page"><section className="portal-shell"><div className="panel-title panel-title-row"><div className="panel-title"><Target size={22}/><div><h1>Growth control center</h1><p className="subtle">Referrals, Founding Grant, cost guards, and the approval-first AI Client Finder.</p></div></div><div className="client-control-row"><a className="icon-btn" href="/owner"><ArrowLeft size={16}/> Owner</a><button className="icon-btn" disabled={busy} onClick={()=>void load()}><RefreshCcw size={16}/> Refresh</button></div></div>{error?<div className="auth-error">{error}</div>:null}{notice?<div className="auth-success">{notice}</div>:null}
  <section className="panel panel-wide"><div className="panel-title"><ShieldAlert size={20}/><div><h2>Launch switches</h2><p className="subtle">Safe defaults remain active. Public referrals, grant enrollment, Stripe, and external email delivery are not enabled by this screen.</p></div></div><div className="client-control-row"><span className="status-summary">Referrals {String(gs.referral_program_enabled?"on":"off")}</span><span className="status-summary">Grant enrollment {String(gs.founding_grant_public_enrollment_enabled?"on":"off")}</span><span className="status-summary">Grant legal review {String(gs.founding_grant_legal_review_complete?"done":"pending")}</span><span className="status-summary">Outreach {String(fs.automation_mode||"review_only")}</span><span className="status-summary">Emergency stop {String(fs.emergency_stop!==false?"on":"off")}</span><span className="status-summary">External delivery {String(fs.external_delivery_enabled?"on":"off")}</span></div></section>
  <div className="owner-detail-grid"><section className="panel panel-wide"><h2>Referral & grant evidence</h2>{Object.entries(g).map(([key,value])=><div className="owner-message-card" key={key}><strong>{key.replaceAll("_"," ")}</strong><span className="subtle">{String(value)}</span></div>)}</section><section className="panel panel-wide"><h2>Client Finder evidence</h2>{Object.entries(f).map(([key,value])=><div className="owner-message-card" key={key}><strong>{key.replaceAll("_"," ")}</strong><span className="subtle">{String(value)}</span></div>)}</section></div>
  <section className="panel panel-wide"><h2>Zero-key discovery QA</h2><p className="subtle">Creates fictional example.invalid prospects with permanent delivery suppression. It performs no web search and sends nothing.</p><div className="setup-form-grid"><label><span>Niche</span><select className="auth-input" value={niche} onChange={e=>setNiche(e.target.value)}><option value="tree_services">Tree services</option><option value="roofing">Roofing</option><option value="auto_services">Auto services</option></select></label><label><span>Fictional geography label</span><input className="auth-input" value={geography} onChange={e=>setGeography(e.target.value)}/></label></div><button className="wide-btn" disabled={busy||geography.trim().length<2} onClick={()=>void fictional()}>Create 5 suppressed fictional prospects</button></section>
  <section className="panel panel-wide"><h2>Recent discovery runs</h2>{(finder.recent_runs||[]).length===0?<div className="empty-state">No runs yet.</div>:(finder.recent_runs||[]).map((row,index)=><div className="owner-message-card" key={String(row.id||index)}><strong>{String(row.run_code||"Run")} · {String(row.mode)}</strong><span className="subtle">{String(row.niche_key).replaceAll("_"," ")} · {String(row.geography)} · imported {String(row.imported_count||0)} · cost ${((Number(row.provider_cost_cents)||0)/100).toFixed(2)}</span></div>)}</section>
  <div className="client-control-row"><a className="wide-btn" href="/owner/sales">Open outreach review pipeline</a><a className="wide-btn" href="/owner/launch-readiness">Open launch readiness</a></div>
  </section></main>;
}
