import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Ban, CheckCircle2, Mail, MessageSquareText, RefreshCcw, Save, Send, ShieldCheck, Target, UserPlus } from "lucide-react";
import { isSupabaseConfigured, supabase } from "../lib/supabaseClient";

type Prospect = {
  id: string; prospect_code: string; business_name: string; niche_key: string; website_url: string | null; city: string | null; state_region: string | null;
  contact_name: string | null; contact_email: string | null; contact_phone: string | null; discord_handle: string | null;
  status: string; priority: string; recommended_tier_key: string; lead_score: number; qualification_signals: Record<string, boolean>;
  research_notes: string | null; next_follow_up_at: string | null; created_at: string;
};
type Permission = { id: string; prospect_id: string; channel: string; status: string; basis: string; evidence_note: string | null; evidence_at: string | null };
type Draft = { id: string; prospect_id: string; channel: string; sequence_step: number; subject: string | null; body: string; rendered_body: string | null; status: string; scheduled_for: string | null; owner_decision_note: string | null; created_at: string };
type Settings = { sender_display_name?: string; sender_email?: string | null; postal_address?: string | null; discord_policy?: string };
type Pipeline = { settings?: Settings; summary?: Record<string, number>; prospects?: Prospect[]; permissions?: Permission[]; drafts?: Draft[]; policy?: Record<string, boolean> };

const signalOptions = [
  ["no_website", "No website"], ["outdated_design", "Outdated design"], ["weak_mobile", "Weak mobile experience"],
  ["weak_contact_path", "Hard to request an estimate"], ["limited_local_seo", "Limited local SEO"], ["missing_service_pages", "Missing service pages"],
] as const;

function outreachTemplate(prospect: Prospect | undefined, channel: string, step: number) {
  const business = prospect?.business_name || "your business";
  const area = [prospect?.city, prospect?.state_region].filter(Boolean).join(", ");
  const businessKind = prospect?.niche_key === "tree_services" ? "tree-service" : "business";
  const detail = prospect?.qualification_signals.no_website
    ? "I couldn't find a clear website for customers to review your services and request an estimate."
    : prospect?.qualification_signals.weak_mobile
      ? "I noticed the current mobile path could make it harder for customers to reach out quickly."
      : "I noticed an opportunity to make your services, service area, and contact path clearer online.";
  if (channel === "sms") return { subject: "", body: `Hi, this is Christian from NXQ Web. Thanks for giving me permission to text. I put together an idea for ${business}'s website${area ? ` in ${area}` : ""}. Want me to send the short preview?` };
  if (channel === "discord") return { subject: "", body: `Hey - Christian from NXQ Web here. Since you opted into the NXQ server, I can share the tree-service website concept for ${business} here if you'd like.` };
  if (step === 2) return { subject: `Quick follow-up for ${business}`, body: `Hi${prospect?.contact_name ? ` ${prospect.contact_name}` : ""},\n\nJust following up on the website idea I sent for ${business}. I can show you a short premium ${businessKind} website example built around clearer services and contact paths.\n\nWould you like me to send the preview?\n\n- Christian` };
  if (step === 3) return { subject: `Should I close this out for ${business}?`, body: `Hi${prospect?.contact_name ? ` ${prospect.contact_name}` : ""},\n\nI don't want to crowd your inbox, so this will be my last follow-up. If improving ${business}'s website becomes a priority, I can show you a premium website concept and the $50-$150 monthly options.\n\nShould I close this out for now?\n\n- Christian` };
  return { subject: `Website idea for ${business}`, body: `Hi${prospect?.contact_name ? ` ${prospect.contact_name}` : ""},\n\nI'm Christian from NXQ Web. ${detail}\n\nNXQ Web builds and hosts premium websites for $50-$150 per month. I can show you a short premium website example built around clear services, mobile contact, and customer inquiries.\n\nWould you like me to send the preview?\n\n- Christian` };
}

export function OwnerSalesPipeline() {
  const [data, setData] = useState<Pipeline>({});
  const [selectedId, setSelectedId] = useState("");
  const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const [senderName, setSenderName] = useState("Christian at NXQ Web"); const [senderEmail, setSenderEmail] = useState(""); const [postalAddress, setPostalAddress] = useState("");
  const [businessName, setBusinessName] = useState(""); const [nicheKey, setNicheKey] = useState("other"); const [websiteUrl, setWebsiteUrl] = useState(""); const [city, setCity] = useState(""); const [stateRegion, setStateRegion] = useState("");
  const [contactName, setContactName] = useState(""); const [contactEmail, setContactEmail] = useState(""); const [contactPhone, setContactPhone] = useState(""); const [sourceUrl, setSourceUrl] = useState(""); const [researchNotes, setResearchNotes] = useState("");
  const [signals, setSignals] = useState<Record<string, boolean>>({});
  const [permissionChannel, setPermissionChannel] = useState("sms"); const [permissionBasis, setPermissionBasis] = useState("explicit_written_consent"); const [permissionEvidence, setPermissionEvidence] = useState("");
  const [draftChannel, setDraftChannel] = useState("email"); const [sequenceStep, setSequenceStep] = useState(1); const [draftSubject, setDraftSubject] = useState(""); const [draftBody, setDraftBody] = useState(""); const [decisionNote, setDecisionNote] = useState("Reviewed for accuracy, relevance, and contact permission.");

  const prospects = data.prospects || []; const permissions = data.permissions || []; const drafts = data.drafts || [];
  const selected = prospects.find((row) => row.id === selectedId) || prospects[0];
  const selectedPermissions = permissions.filter((row) => row.prospect_id === selected?.id);
  const selectedDrafts = drafts.filter((row) => row.prospect_id === selected?.id);
  const channelPermission = useMemo(() => selectedPermissions.find((row) => row.channel === draftChannel), [selectedPermissions, draftChannel]);

  const load = useCallback(async () => {
    if (!isSupabaseConfigured || !supabase) { setError("Supabase is not configured yet."); return; }
    setBusy(true); setError("");
    const result = await supabase.rpc("owner_sales_pipeline");
    setBusy(false);
    if (result.error) { setError(result.error.message); return; }
    const next = (result.data || {}) as Pipeline; setData(next);
    setSenderName(next.settings?.sender_display_name || "Christian at NXQ Web"); setSenderEmail(next.settings?.sender_email || ""); setPostalAddress(next.settings?.postal_address || "");
    if (next.prospects?.[0]) setSelectedId(current => current || next.prospects?.[0]?.id || "");
  }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const template = outreachTemplate(selected, draftChannel, sequenceStep); setDraftSubject(template.subject); setDraftBody(template.body); }, [selected, draftChannel, sequenceStep]);

  async function call(name: string, args: Record<string, unknown>, success: string) {
    if (!supabase) return; setBusy(true); setError(""); setNotice("");
    const result = await supabase.rpc(name, args); setBusy(false);
    if (result.error) { setError(result.error.message); return; }
    setNotice(success); await load();
  }
  async function saveSettings() { await call("owner_update_sales_outreach_settings", { target_sender_display_name: senderName, target_sender_email: senderEmail, target_postal_address: postalAddress }, "Outbound identity saved. Email approval remains blocked until the sender email and postal address are complete."); }
  async function addProspect() {
    await call("owner_create_sales_prospect", { target_business_name: businessName, target_niche_key: nicheKey, target_website_url: websiteUrl, target_city: city, target_state_region: stateRegion, target_contact_name: contactName, target_contact_email: contactEmail, target_contact_phone: contactPhone, target_source_url: sourceUrl, target_signals: signals, target_notes: researchNotes }, "Prospect scored and added.");
    setBusinessName(""); setNicheKey("other"); setWebsiteUrl(""); setCity(""); setStateRegion(""); setContactName(""); setContactEmail(""); setContactPhone(""); setSourceUrl(""); setResearchNotes(""); setSignals({});
  }
  async function recordPermission() { if (!selected) return; await call("owner_record_sales_permission", { target_prospect_id: selected.id, target_channel: permissionChannel, target_status: "allowed", target_basis: permissionBasis, target_evidence_note: permissionEvidence, target_evidence_source: sourceUrl || null }, `${permissionChannel.toUpperCase()} permission evidence recorded.`); setPermissionEvidence(""); }
  async function createDraft() { if (!selected) return; await call("owner_create_sales_outreach_draft", { target_prospect_id: selected.id, target_channel: draftChannel, target_sequence_step: sequenceStep, target_subject: draftSubject, target_body: draftBody, target_scheduled_for: null }, "Draft created for owner review. Nothing was sent."); }
  async function decide(draft: Draft, decision: "approve" | "reject") { await call("owner_decide_sales_outreach_draft", { target_draft_id: draft.id, target_decision: decision, target_note: decisionNote }, decision === "approve" ? "Draft approved for a manual send. Nothing was sent automatically." : "Draft rejected."); }
  async function markSent(draft: Draft) { await call("owner_mark_sales_outreach_sent", { target_draft_id: draft.id, target_sent_at: new Date().toISOString() }, "Manual send recorded and the next follow-up date calculated."); }
  async function optOut() { if (!selected) return; await call("owner_record_sales_opt_out", { target_prospect_id: selected.id, target_reason: decisionNote }, "Do-not-contact hard stop applied across email, SMS, and Discord."); }

  return <main className="nxq-page"><section className="portal-shell">
    <div className="panel-title panel-title-row"><div className="panel-title"><Target size={22}/><div><h1>NXQ sales pipeline</h1><p className="subtle">Nationwide prospecting for legitimate businesses without websites, with owner-approved outreach and all-channel opt-out enforcement. Tree Services remains the flagship demo.</p></div></div><div className="client-control-row"><a className="icon-btn" href="/owner"><ArrowLeft size={16}/> Owner</a><button className="icon-btn" disabled={busy} onClick={() => void load()} type="button"><RefreshCcw size={16}/> Refresh</button></div></div>
    {error ? <div className="auth-error" role="alert">{error}</div> : null}{notice ? <div className="auth-success"><CheckCircle2 size={16}/> {notice}</div> : null}
    <div className="portal-grid">{[["Prospects",data.summary?.total||0],["Qualified",data.summary?.qualified||0],["Needs review",data.summary?.needs_review||0],["Follow-ups due",data.summary?.follow_ups_due||0],["Do not contact",data.summary?.do_not_contact||0]].map(([label,value])=><section className="panel" key={String(label)}><h2>{label}</h2><div className="status-summary">{value}</div></section>)}</div>
    <section className="panel panel-wide"><div className="panel-title"><ShieldCheck size={20}/><div><h2>Outbound identity and safety lock</h2><p className="subtle">Cold SMS and cold Discord DMs are blocked. Email approval requires a real sender email, postal address, truthful subject, and opt-out footer.</p></div></div><div className="setup-form-grid"><label><span>Sender name</span><input className="auth-input" value={senderName} onChange={e=>setSenderName(e.target.value)}/></label><label><span>Sender email</span><input className="auth-input" type="email" value={senderEmail} onChange={e=>setSenderEmail(e.target.value)}/></label><label><span>Valid physical postal address</span><input className="auth-input" value={postalAddress} onChange={e=>setPostalAddress(e.target.value)} placeholder="Required before email approval"/></label></div><button className="wide-btn" disabled={busy} onClick={()=>void saveSettings()} type="button"><Save size={16}/> Save outbound identity</button></section>
    <section className="panel panel-wide"><div className="panel-title"><UserPlus size={20}/><div><h2>Add a no-website business prospect</h2><p className="subtle">Target any legitimate U.S. business without a website. Enter only public business information you personally reviewed; scoring uses visible website gaps, never private or sensitive data.</p></div></div><div className="setup-form-grid"><label><span>Business name</span><input className="auth-input" value={businessName} onChange={e=>setBusinessName(e.target.value)}/></label><label><span>Industry</span><select className="auth-input" value={nicheKey} onChange={e=>setNicheKey(e.target.value)}><option value="tree_services">Tree Services</option><option value="roofing">Roofing</option><option value="auto_services">Auto / detailing</option><option value="home_services">Other home services</option><option value="professional_services">Professional services</option><option value="health_wellness">Health / wellness</option><option value="food_hospitality">Food / hospitality</option><option value="retail">Retail</option><option value="other">Other</option></select></label><label><span>Website (leave blank if none)</span><input className="auth-input" value={websiteUrl} onChange={e=>setWebsiteUrl(e.target.value)}/></label><label><span>City</span><input className="auth-input" value={city} onChange={e=>setCity(e.target.value)}/></label><label><span>State</span><input className="auth-input" value={stateRegion} onChange={e=>setStateRegion(e.target.value)}/></label><label><span>Contact name</span><input className="auth-input" value={contactName} onChange={e=>setContactName(e.target.value)}/></label><label><span>Public business email</span><input className="auth-input" type="email" value={contactEmail} onChange={e=>setContactEmail(e.target.value)}/></label><label><span>Public business phone</span><input className="auth-input" value={contactPhone} onChange={e=>setContactPhone(e.target.value)}/></label><label><span>Research source URL</span><input className="auth-input" value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)}/></label><label><span>Research notes</span><textarea className="auth-input" rows={3} value={researchNotes} onChange={e=>setResearchNotes(e.target.value)}/></label></div><div className="client-control-row">{signalOptions.map(([key,label])=><label className="icon-btn" key={key}><input type="checkbox" checked={Boolean(signals[key])} onChange={e=>setSignals(current=>({...current,[key]:e.target.checked}))}/>{label}</label>)}</div><button className="wide-btn" disabled={busy||businessName.trim().length<2} onClick={()=>void addProspect()} type="button"><UserPlus size={16}/> Score and add prospect</button></section>
    <div className="owner-detail-grid"><section className="panel panel-wide"><h2>Prospects</h2>{prospects.length===0?<div className="empty-state">No NXQ prospects yet.</div>:prospects.map(row=><button className={row.id===selected?.id?"owner-message-card selected-message":"owner-message-card"} key={row.id} onClick={()=>setSelectedId(row.id)} type="button"><strong>{row.business_name}</strong><span className="subtle">{row.prospect_code} · Score {row.lead_score} · {row.recommended_tier_key} · {row.status.replaceAll("_"," ")}</span>{row.next_follow_up_at?<span className="subtle">Follow-up {new Date(row.next_follow_up_at).toLocaleString()}</span>:null}</button>)}</section>
    <section className="panel panel-wide"><h2>{selected?.business_name||"Select a prospect"}</h2>{selected?<><p className="subtle">{selected.niche_key.replaceAll("_"," ")} · {[selected.city,selected.state_region].filter(Boolean).join(", ")} · Score {selected.lead_score} · {selected.priority} priority</p><p>{selected.research_notes||"No research notes yet."}</p><div className="client-control-row">{selectedPermissions.map(row=><span className="status-summary" key={row.id}>{row.channel}: {row.status} · {row.basis.replaceAll("_"," ")}</span>)}</div><label><span>Decision / evidence note</span><input className="auth-input" value={decisionNote} onChange={e=>setDecisionNote(e.target.value)}/></label><button className="icon-btn danger-btn" disabled={busy||selected.status==="do_not_contact"} onClick={()=>void optOut()} type="button"><Ban size={16}/> Record opt-out / do not contact</button></>:<div className="empty-state">Add or select a prospect.</div>}</section></div>
    {selected?<><section className="panel panel-wide"><div className="panel-title"><ShieldCheck size={20}/><div><h2>Record permission</h2><p className="subtle">SMS and Discord cannot be approved without specific opt-in or relationship evidence.</p></div></div><div className="setup-form-grid"><label><span>Channel</span><select className="auth-input" value={permissionChannel} onChange={e=>setPermissionChannel(e.target.value)}><option value="sms">Business text</option><option value="discord">Discord</option><option value="email">Email</option></select></label><label><span>Basis</span><select className="auth-input" value={permissionBasis} onChange={e=>setPermissionBasis(e.target.value)}><option value="explicit_written_consent">Explicit written consent</option><option value="opt_in">Opt in</option><option value="direct_request">Direct request</option><option value="existing_relationship">Existing relationship</option><option value="public_business_email">Public business email</option></select></label><label><span>Evidence</span><input className="auth-input" value={permissionEvidence} onChange={e=>setPermissionEvidence(e.target.value)} placeholder="Where, when, and what they agreed to"/></label></div><button className="wide-btn" disabled={busy||permissionEvidence.trim().length<8} onClick={()=>void recordPermission()} type="button"><ShieldCheck size={16}/> Record permission evidence</button></section>
    <section className="panel panel-wide"><div className="panel-title"><MessageSquareText size={20}/><div><h2>Draft outreach</h2><p className="subtle">Templates personalize from owner-reviewed facts. Drafting never sends.</p></div></div><div className="setup-form-grid"><label><span>Channel</span><select className="auth-input" value={draftChannel} onChange={e=>setDraftChannel(e.target.value)}><option value="email">Email</option><option value="sms">Business text</option><option value="discord">Discord</option></select></label><label><span>Sequence step</span><select className="auth-input" value={sequenceStep} onChange={e=>setSequenceStep(Number(e.target.value))}><option value={1}>First message</option><option value={2}>Follow-up</option><option value={3}>Final close-out</option></select></label><label><span>Permission</span><input className="auth-input" readOnly value={channelPermission?`${channelPermission.status} · ${channelPermission.basis.replaceAll("_"," ")}`:"No permission record"}/></label><label><span>Subject</span><input className="auth-input" disabled={draftChannel!=="email"} value={draftSubject} onChange={e=>setDraftSubject(e.target.value)}/></label><label><span>Message</span><textarea className="auth-input" rows={8} value={draftBody} onChange={e=>setDraftBody(e.target.value)}/></label></div><button className="wide-btn" disabled={busy||draftBody.trim().length<10} onClick={()=>void createDraft()} type="button">{draftChannel==="email"?<Mail size={16}/>:<MessageSquareText size={16}/>} Create review draft</button></section>
    <section className="panel panel-wide"><h2>Drafts and approvals</h2>{selectedDrafts.length===0?<div className="empty-state">No drafts for this prospect.</div>:selectedDrafts.map(draft=><article className="owner-message-card" key={draft.id}><div className="panel-title panel-title-row"><div><strong>{draft.channel.toUpperCase()} · Step {draft.sequence_step}</strong><p className="subtle">{draft.status.replaceAll("_"," ")} · {new Date(draft.created_at).toLocaleString()}</p></div><span className="status-summary">{draft.status}</span></div>{draft.subject?<p><strong>Subject:</strong> {draft.subject}</p>:null}<pre style={{whiteSpace:"pre-wrap",fontFamily:"inherit"}}>{draft.rendered_body||draft.body}</pre><div className="client-control-row">{draft.status==="needs_review"?<><button className="icon-btn" disabled={busy} onClick={()=>void decide(draft,"approve")} type="button"><CheckCircle2 size={16}/> Approve</button><button className="icon-btn danger-btn" disabled={busy} onClick={()=>void decide(draft,"reject")} type="button"><Ban size={16}/> Reject</button></>:null}{draft.status==="approved"?<button className="wide-btn" disabled={busy} onClick={()=>void markSent(draft)} type="button"><Send size={16}/> Mark manually sent</button>:null}</div></article>)}</section></>:null}
  </section></main>;
}
