import { useEffect, useState } from "react";
import { ArrowLeft, Cable, CheckCircle2, CircleAlert, Power, RefreshCcw } from "lucide-react";
import { isSupabaseConfigured, supabase } from "../lib/supabaseClient";

type Provider={id:string;provider_key:string;provider_category:string;scope_type:string;status:string;adapter_version:string;capabilities:string[];required_secret_names:string[];last_checked_at:string|null;last_success_at:string|null;last_error:string|null};

export function OwnerProviderHealth(){
  const [rows,setRows]=useState<Provider[]>([]);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [busyId,setBusyId]=useState<string|null>(null);
  async function load(){if(!isSupabaseConfigured||!supabase)return;const r=await supabase.from("nxq_provider_connections").select("id,provider_key,provider_category,scope_type,status,adapter_version,capabilities,required_secret_names,last_checked_at,last_success_at,last_error").order("provider_category").order("provider_key");if(r.error){setError(r.error.message);return;}setRows((r.data||[]) as Provider[]);}
  useEffect(()=>{let active=true;async function initial(){if(!active)return;await load();}void initial();return()=>{active=false;};},[]);
  async function recheck(row:Provider){if(!supabase)return;setBusyId(row.id);setError("");setNotice("");const r=await supabase.rpc("owner_request_provider_recheck",{target_connection_id:row.id});if(r.error)setError(r.error.message);else{setNotice(`${row.provider_key} was queued for a fresh health check.`);await load();}setBusyId(null);}
  async function toggle(row:Provider){if(!supabase)return;const enable=row.status==="disabled";setBusyId(row.id);setError("");setNotice("");const r=await supabase.rpc("owner_set_provider_enabled",{target_connection_id:row.id,target_enabled:enable,target_reason:enable?null:"Disabled from NXQ Provider Health."});if(r.error)setError(r.error.message);else{setNotice(`${row.provider_key} is now ${enable?"enabled and ready to recheck":"disabled"}.`);await load();}setBusyId(null);}
  return <main className="nxq-page"><section className="portal-shell"><div className="panel-title panel-title-row"><div className="panel-title"><Cable size={22}/><div><h1>Provider health</h1><p className="subtle">Connection state and capabilities only. Secret values are never displayed or edited here.</p></div></div><a className="icon-btn" href="/owner"><ArrowLeft size={16}/> Owner</a></div>{error?<div className="auth-error" role="alert">{error}</div>:null}{notice?<div className="auth-success">{notice}</div>:null}<section className="panel panel-wide">{rows.length===0?<div className="empty-state">No provider connections registered yet. Runtime setup will populate this registry.</div>:rows.map(row=><article className="owner-message-card" key={row.id}><div className="panel-title panel-title-row"><div className="panel-title">{row.status==="healthy"?<CheckCircle2 size={18}/>:<CircleAlert size={18}/>}<div><strong>{row.provider_key}</strong><p className="subtle">{row.provider_category} · {row.scope_type} · adapter {row.adapter_version}</p></div></div><span className="status-summary">{row.status.replaceAll("_"," ")}</span></div><p className="subtle">Capabilities: {row.capabilities?.length?row.capabilities.join(", "):"none registered"}</p><p className="subtle">Required secret names: {row.required_secret_names?.length?row.required_secret_names.join(", "):"none"}</p>{row.last_error?<div className="auth-error">{row.last_error}</div>:null}{row.last_success_at?<p className="subtle">Last success: {new Date(row.last_success_at).toLocaleString()}</p>:null}<div className="client-control-row" style={{marginTop:"0.85rem"}}><button className="icon-btn" type="button" disabled={busyId===row.id||row.status==="disabled"} onClick={()=>void recheck(row)}><RefreshCcw size={15}/>{busyId===row.id?"Working...":"Recheck now"}</button><button className={row.status==="disabled"?"icon-btn":"icon-btn danger-btn"} type="button" disabled={busyId===row.id} onClick={()=>void toggle(row)}><Power size={15}/>{row.status==="disabled"?"Enable + recheck":"Disable"}</button></div></article>)}</section></section></main>;
}
